apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ftc-app-development

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

replicas:
  - name: billing-service
    count: 1

configMapGenerator:
  - name: billing-service-config
    behavior: merge
    literals:
      - DYNAMODB_BUDGETS_TABLE=fiap-tech-challenge-budgets-development
      - DYNAMODB_PAYMENTS_TABLE=fiap-tech-challenge-payments-development
      - EVENT_BUS_NAME=fiap-tech-challenge-events-development
      - SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/305032652600/billing-service-events-development

images:
  - name: billing-service
    newName: 305032652600.dkr.ecr.us-east-1.amazonaws.com/billing-service
    newTag: dev-latest

patches:
  - target:
      kind: ServiceAccount
      name: billing-service
    patch: |-
      - op: replace
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::305032652600:role/fiap-billing-service-dev
